openapi: 3.1.0
info:
  version: 1.0.0
  title: 'AquaTrack'
  description: This is the documentation for AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://127.0.0.1:3000         #127.0.0.1:3000
tags:
  - name: Water
    description: Operations related to water tracking.
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
paths:
  /water/{id}:
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml 
    get:
      $ref: ../swagger/paths/water/{id}/get.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
    get: 
      $ref: ../swagger/paths/water/get.yaml