openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
servers:
  - url: http://localhost:5173
  - url: http://localhost:3000
  - url: https://aquadev-back.onrender.com/

tags:
  - name: Users
    description: Login User API Route
paths:
  /users/login:
    post:
      $ref: ../swagger/paths/users/auth/login.yaml
  /users/register:
    post:
      $ref: ../swagger/paths/users/auth/register.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/auth/refresh.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/auth/logout.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/auth/update.yaml
  /users/google/url:
    get:
      $ref: ../swagger/paths/users/auth/google/googleURL.yaml
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    post:
      $ref: ../swagger/paths/users/post.yaml
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
