openapi: 3.1.0
info:
  version: 1.0.0
  title: 'AquaTrack'
  description: This is the documentation for AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000
  - url: https://aquadev-back.onrender.com/
tags:
  - name: Water
    description: Operations related to water tracking.
paths:
  /users/login:
    post:
      $ref: ../swagger/paths/users/auth/login.yaml
  /users/register:
    post:
      $ref: ../swagger/paths/users/auth/register.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/auth/refresh.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/auth/logout.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/auth/update.yaml
  /users/google/url:
    get:
      $ref: ../swagger/paths/users/auth/google/googleURL.yaml
  /users/google/callback:
    post:
      $ref: ../swagger/paths/users/auth/google/googleCallback.yaml
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml
  /water/{id}:
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml 
    get:
      $ref: ../swagger/paths/water/{id}/get.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
    get: 
      $ref: ../swagger/paths/water/get.yaml
 components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT