openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
paths:
  /users/login:
    post:
      $ref: ../swagger/paths/users/auth/login.yaml
  /users/register:
    post:
      $ref: ../swagger/paths/users/auth/register.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/auth/refresh.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/auth/logout.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/auth/update.yaml
  /users/google/url:
    get:
      $ref: ../swagger/paths/users/auth/google/googleURL.yaml
  /users/google/callback:
    post:
      $ref: ../swagger/paths/users/auth/google/googleCallback.yaml
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
